### ISSUE TITLE
Pushing all branches

### ISSUE THREAD

**Issue by aureq** [RalfJung/git-mirror#2]
Hi @RalfJung 

I've been using `git-mirror` for a few weeks now and it works really well. Thank you for that.

I have a few repositories that I'm pushing to github as and some of them have multiple branches. I'm wondering if there's a way when the very first push is done with the gitolite hook active to push all references (`--all`) ?

Similarly, when I remove a branch in gitolite, I'm wondering if there's a way to remote the remote branch too (`--prune`).

Thanks

**Comment by RalfJung** [comment]
> I have a few repositories that I'm pushing to github as and some of them have multiple branches. I'm wondering if there's a way when the very first push is done with the gitolite hook active to push all references (--all) ?

For one-off things, IMO it makes more sense for the user to just do that themselves, doesn't it? But this seems like a good addition to the documentation.

> Similarly, when I remove a branch in gitolite, I'm wondering if there's a way to remote the remote branch too (--prune).

Branch deletion [is implemented](https://github.com/RalfJung/git-mirror/blob/5974240009d223b88e8de66a11aaa006e2706211/git_mirror.py#L187) and worked for me last time I tried it. What exactly are you doing and what is (not) happening?

**Comment by aureq** [comment]
Thanks for following up.

My apologies, I didn't realize the deletion was supported. 

Also, thank you for updating the one-off push all-refs. 

Cheers
